# fly.toml app configuration file generated for bsky-feedgen-sieve on 2023-07-05T17:09:50-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bsky-feedgen-api"
primary_region = "ord"

[env]
  BSKY_USERNAME = "trezy.codes"
  FEEDGEN_HOSTNAME = "bsky-feeds.trezy.studio"
  LOG_LEVEL = "silly"
  OWNER_DID = "did:plc:4jrld6fwpnwqehtce56qshzv"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  auto_stop_machines = false
  auto_start_machines = true
  force_https = true
  internal_port = 3000
  min_machines_running = 1
  processes = ["app"]

[metrics]
  path = "/metrics"
  port = 9091
