# fly.toml app configuration file generated for bsky-feedgen-sieve on 2023-07-05T17:09:50-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bsky-feedgen-sieve"
primary_region = "ord"

[build]
  dockerfile = "./Dockerfile"

[env]
  BSKY_SERVICE_URL = "bsky.social"
  LOG_LEVEL = "silly"
  METRICS_PREFIX = "bsky_feedgen_sieve_"
  MQ_PREFETCH_COUNT = 5
  MQ_TIMEOUT = 15000
  MQ_URL = "amqp://bsky-feedgen-rabbitmq.internal"

[http_service]
  auto_stop_machines = false
  auto_start_machines = false
  force_https = true
  internal_port = 3000
  min_machines_running = 1
  processes = ["app"]

[metrics]
  path = "/metrics"
  port = 3000
