name: Deploy API to Fly.io
on:
  push:
    branches:
      - main
    paths:
      - 'packages/api/**/*'
      - 'packages/common/**/*'
      - 'packages/feeds/**/*'
      - 'packages/lib/**/*'
      - 'packages/koa-api/**/*'

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config ./packages/api/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_API }}
